### PR TITLE
Re-enable reconnection

### PR DESCRIPTION
**Pull request by YaManicKill**

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
This seems useful for development. What are the tradeoffs of doing this in production?

**Comment by YaManicKill** [comment]
Why would we not do this in production? We used to do it, they changed the default. This means that if the server dies, or the client can't see the server, it will try to reconnect to the server. If we don't do this, the client loses its connection (say a mobile loses signal) and it has to refresh the page to work.

**Comment by not-an-aardvark** [comment]
> Why would we not do this in production?

I'm not sure -- it just seems like there must be some downside to this option, otherwise it would still be on by default. I'll look at the release notes.

**Comment by not-an-aardvark** [comment]
Just looked at [this discussion](https://github.com/balderdashy/sails.io.js/commit/7f8c7a2d6d7430725bca5383f4b80570e038ab81#commitcomment-20152044). Seems like reconnecting should be fine for our purposes.

**Pull request merged**
